name: 'setup node'
description: 'setup node and install dependencies'

inputs:
  node-version:
    description: 'node version to use'
    required: false
    default: '24.x'
  cache:
    description: 'cache to use (npm/yarn)'
    required: false
    default: 'npm'
  clean-install:
    description: 'if a clean has to be performed'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: 'validate cache input'
      shell: bash
      run: |
        if [[ "${{ inputs.cache }}" != "npm" && "${{ inputs.cache }}" != "yarn"]]
          echo "Error. Cache must be either 'npm' or 'yarn'"
          exit 1
        fi

    - name: 'setup node'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: 'install dependencies'
      shell: bash
      run: |
        if [ "${{ inputs.clean-install }}" = "true" ]; then
          rm -rf node_modules package-lock.json
          npm install
        else
          npm ci
        fi

    - name: 'build'
      shell: bash
      run: npm run build
