name: caller.yaml
on:
  workflow_dispatch:
    inputs:
      feature:
        description: "which feature to deploy"
        required: true
        type: choice
        options:
          - class_schedule
          - membership
          - training
jobs:
  classschedule:
    if: github.event.inputs.feature == 'class_schedule'
    uses: ./.github/workflows/class_schedule.yaml

  membership:
    if: github.event.inputs.feature == 'membership'
    uses: ./.github/workflows/membership.yaml

  training:
    if: github.event.inputs.feature == 'training'
    uses: ./.github/workflows/training.yaml
